#!/usr/bin/env bash

function error() {
	echo "$1"
	exit
}

# TODO: select all possible libretro cores for this console
CORE_NES="/usr/lib/libretro/mesen_libretro.so"
SHADER_DIR="/usr/share/libretro/shaders/Mega_Bezel_Packs/Duimon-Mega-Bezel/Presets/Advanced"

# TODO: PVM20 & PVM20 Night needs to be flipped vertically
NES_SHADER_PATH="$SHADER_DIR/Nintendo_NES/NES-[ADV]-[Guest]-[PVM20]-[Night].slangp"

ROM_BASE_DIR="$HOME/share/games/nes"

ROM_FILE=$(find "$ROM_BASE_DIR" -type f -iname "*.zip" -printf "%f\n" | dmenu -i -l 40 | awk -F"\"[,:]* *\"*" '{ print $1; }')

ROM_PATH="$ROM_BASE_DIR/$ROM_FILE"

[[ ! -z $ROM_FILE ]] && [[ -f $ROM_PATH ]] || error "ROM file not selected or doesn't exists"
[[ -f $CORE_NES ]] || error "Core not found or doesn't exists"

retroarch -L $CORE_NES --set-shader=$NES_SHADER_PATH "$ROM_PATH" &
